// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3oIYIML9hNpQLK9VdA0lj7JZXm9q8ZAE',
    appId: '1:1084960455318:web:dfbcc4b12446ea5430e0b7',
    messagingSenderId: '1084960455318',
    projectId: 'remindme-c7bba',
    authDomain: 'remindme-c7bba.firebaseapp.com',
    storageBucket: 'remindme-c7bba.appspot.com',
    measurementId: 'G-PJ852JDG3E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcj_64pNVdgsui2ODhv24EVrkhZHGOAVM',
    appId: '1:1084960455318:android:f679f4263cb53c4630e0b7',
    messagingSenderId: '1084960455318',
    projectId: 'remindme-c7bba',
    storageBucket: 'remindme-c7bba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlVkNTNLqGBPXdaHhvgbC8Azt2rzuEi38',
    appId: '1:1084960455318:ios:23f2556da515612a30e0b7',
    messagingSenderId: '1084960455318',
    projectId: 'remindme-c7bba',
    storageBucket: 'remindme-c7bba.appspot.com',
    androidClientId: '1084960455318-uuto9p2rnqis719ho41cm1ru78568hns.apps.googleusercontent.com',
    iosClientId: '1084960455318-dp26rgv1a8p3a5349dnng5gemn1oc8hq.apps.googleusercontent.com',
    iosBundleId: 'com.example.ughhagain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlVkNTNLqGBPXdaHhvgbC8Azt2rzuEi38',
    appId: '1:1084960455318:ios:23f2556da515612a30e0b7',
    messagingSenderId: '1084960455318',
    projectId: 'remindme-c7bba',
    storageBucket: 'remindme-c7bba.appspot.com',
    androidClientId: '1084960455318-uuto9p2rnqis719ho41cm1ru78568hns.apps.googleusercontent.com',
    iosClientId: '1084960455318-dp26rgv1a8p3a5349dnng5gemn1oc8hq.apps.googleusercontent.com',
    iosBundleId: 'com.example.ughhagain',
  );
}
